<a href="https://colab.research.google.com/github/juubair-islam/CSE317L-Numerical-Lab/blob/Assignment-1/Lab_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/mirsazzathossain/CSE317-Lab/blob/main/Lab_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np


#### **Homework 01:**
Generate random matrix of size 10 x 5. Then, solve the following problems:

In [16]:
# Write your code to create the 10x5 random matrix here

matrix = np.random.randint(0, 101, size=(10, 5))
print(matrix)

[[37 21 44 71 61]
 [13 41 18 96 84]
 [ 6 95 44 96  0]
 [97 87 94 60 54]
 [38  6 41 19 75]
 [53 40 62 34 28]
 [42 89 16 20 17]
 [85 71 67  1  0]
 [71 99 40 17 10]
 [19 10 38 37 14]]


##### **Problem 01:**
Calculate the sum and mean of the 2nd row of the matrix.

In [2]:
# Write your code here

##### **Problem 02:**
Find the sum and mean of all the rows of the matrix.

In [3]:
# Write your code here

##### **Problem 03:**
Find the mean of the 3rd column of the matrix without using the built-in function and loop.

In [4]:
# Write your code here

##### **Problem 04:**
Generate the vector `[25, 16, 9, 4, 1]` and then find the square root of each element of the vector using for loop. **Hint:** Use `np.sqrt()` function to find the square root of a number, don't use any other built-in function.

In [5]:
# Write your code here

##### **Problem 05:**
Write a function that takes a number and returns a vector like the previous problem. For example, if the input is 5, then the output should be `[25, 16, 9, 4, 1]`. If the input is 10, then the output should be `[100, 81, 64, 49, 36, 25, 16, 9, 4, 1]`.

In [6]:
# Write your code here

##### **Problem 06:**
Generate the following block matrix:

$$
\begin{bmatrix}
1 & 0 & 0 & 2 & 2 \\
0 & 1 & 0 & 2 & 2 \\
0 & 0 & 1 & 2 & 2 \\
25 & 16 & 9 & 4 & 1 \\
\end{bmatrix}
$$

You can use any built-in function to generate the matrix.

In [7]:
# Write your code here

##### **Problem 07:**
Plot $y = 2x^2 + 3x + 1$ for $x \in [-3, 3]$ with interval 0.25. You can use any built-in function to plot the graph.

In [8]:
# Write your code here

##### **Problem 08:**
Plot $x + y + z = 1$ for $x, y \in [-3, 3]$ with interval 0.5. Use meshgrid to generate the grid. You can use any built-in function to plot the surface.

In [9]:
# Write your code here

##### **Problem 09:**
Download the image of Lena Forsen from the following link: [https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png](https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png). Then, do the following tasks:

*  Load the image to a numpy array.
*  Find the size of the image.
*  Find the minimum and maximum value of the image.
*  Find the mean and standard deviation of the image.
*  Plot the image using `plt.imshow()` or `display()`.
*  Resize the image to 50 x 50.
*  Convert the image to grayscale.
*  Plot the grayscale image using `plt.imshow()` or `display()`.
*  Save the grayscale image using `imsave()`.
*  Stack the columns of the image to form a vector of size 2500 x 1.

In [10]:
# Write your code here

##### **Problem 10:**
Compute 2nd order Taylor approximation of $e^{2x}$ and $e^{3x}$, and $e^{5x}$ around $a = 0$ for $x \in [-1, 1]$ with interval 0.01. Then, determine which of the following is more accurate:
> 1. Calculating the Taylor approximation separately for each $e^{2x}$, $e^{3x}$ then multiplying them together.
> 2. Calculating the Taylor approximation for $e^{5x}$.

Use mean square error (MSE) to determine the accuracy. Also, plot the Taylor approximation for 1st and 2nd method and the original function in the same plot for visual comparison.

In [11]:
# Write your code here